import { useQuery } from '@tanstack/react-query';
import { Button, FormField, Input, Select } from '@sdlc/ui/ui';
import type { Connection, ProfileInput } from '../../shared/api/client';
import { providerKeys, readCatalog, readModelContext } from '../providers/service';
function TargetFields({ value, index, connections, onChange }: {
    value: ProfileInput['deployments'][number];
    index: number;
    connections: Connection[];
    onChange: (value: ProfileInput['deployments'][number]) => void;
}) {
    const catalog = useQuery({ queryKey: providerKeys.catalog(value.connection_id, value.generation, ''), queryFn: ({ signal }) => readCatalog(value.connection_id, '', undefined, signal), enabled: !!value.connection_id });
    const context = useQuery({ queryKey: providerKeys.context(value.connection_id, value.model_id), queryFn: ({ signal }) => readModelContext(value.connection_id, value.model_id, signal), enabled: !!value.connection_id && !!value.model_id });
    const current = connections.find(c => c.id === value.connection_id);
    return <div className="grid min-w-0 gap-4 md:grid-cols-2"><FormField id={`profile-connection-${index}`} label="Подключение" required>{attrs => <Select {...attrs} value={value.connection_id} onChange={e => {
                const c = connections.find(c => c.id === e.target.value);
                if (c)
                    onChange({ ...value, connection_id: c.id, generation: c.generation });
            }}><option value="">Выберите подключение</option>{connections.map(c => <option key={c.id} value={c.id}>{c.display_name}</option>)}{value.connection_id && !connections.some(c => c.id === value.connection_id) && <option value={value.connection_id}>{value.connection_id}</option>}</Select>}</FormField><FormField id={`profile-generation-${index}`} label="Поколение авторизации" hint="Закреплено в черновике; смена подключения выбирает его текущее поколение.">{attrs => <><Input {...attrs} readOnly value={value.generation}/>{current && current.generation !== value.generation && <Button type="button" variant="outline" onClick={() => onChange({ ...value, generation: current.generation })}>Использовать текущее поколение {current.generation}</Button>}</>}</FormField><FormField id={`profile-model-${index}`} label="Точный model ID" required hint="Каталог содержит объявления моделей. Доступ и capabilities подтверждаются проверкой.">{attrs => <><Input {...attrs} list={`profile-catalog-${index}`} value={value.model_id} maxLength={256} onChange={e => onChange({ ...value, model_id: e.target.value })}/><datalist id={`profile-catalog-${index}`}>{(catalog.data?.generation === value.generation ? catalog.data.models : []).map(m => <option key={m.provider_model_id} value={m.provider_model_id}/>)}</datalist></>}</FormField><p className="self-center text-sm text-text-secondary">{context.isError ? 'Не удалось прочитать сохранённый контекст.' : context.data?.preference ? `Контекст подключения: ${context.data.preference.context_window_tokens} токенов (v${context.data.version}).` : 'Контекст подключения не задан.'}</p>{catalog.isError && <p className="text-sm text-danger">Каталог недоступен; точный model ID можно сохранить в черновике.</p>}</div>;
}
export function ProfileFields({ value, onChange, connections, disabled = false, existing = false }: {
    value: ProfileInput;
    onChange: (value: ProfileInput) => void;
    connections: Connection[];
    disabled?: boolean;
    existing?: boolean;
}) {
    function set<K extends keyof ProfileInput>(key: K, next: ProfileInput[K]) { onChange({ ...value, [key]: next }); }
    const caps: ProfileInput['required_capabilities'][number][] = ['text', 'stream', 'function_tools', 'json_schema', 'responses', 'cancel'];
    const overrides: NonNullable<ProfileInput['allowed_overrides']>[number][] = ['temperature', 'top_p', 'max_output_tokens', 'reasoning_effort'];
    return <fieldset disabled={disabled} className="min-w-0 space-y-6 border-0 p-0"><div className="grid gap-4 md:grid-cols-2"><FormField id="profile-slug" label="Slug" required hint="Стабильное имя для клиентов: латинские строчные буквы, цифры и дефис.">{attrs => <Input {...attrs} readOnly={existing} value={value.slug} maxLength={63} onChange={e => set('slug', e.target.value)}/>}</FormField><FormField id="profile-name" label="Название профиля" required>{attrs => <Input {...attrs} value={value.display_name} maxLength={120} onChange={e => set('display_name', e.target.value)}/>}</FormField><FormField id="profile-mode" label="Режим" required>{attrs => <Select {...attrs} value={value.mode} onChange={e => set('mode', e.target.value as ProfileInput['mode'])}><option value="development">Разработка — ordered fallback</option><option value="pinned_test">Pinned test — один deployment</option></Select>}</FormField></div>
  <section aria-label="Порядок deployments" className="space-y-4"><h3 className="font-semibold">Порядок deployments</h3>{value.deployments.map((target, i) => <div className="min-w-0 rounded-lg border border-border p-4" key={i}><h4 className="mb-3 font-medium">Deployment {i + 1}</h4><TargetFields value={target} index={i} connections={connections} onChange={t => set('deployments', value.deployments.map((d, j) => j === i ? t : d))}/><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={i === 0} onClick={() => { const next = [...value.deployments]; [next[i - 1], next[i]] = [next[i]!, next[i - 1]!]; set('deployments', next); }}>Выше</Button><Button type="button" variant="outline" disabled={i === value.deployments.length - 1} onClick={() => { const next = [...value.deployments]; [next[i + 1], next[i]] = [next[i]!, next[i + 1]!]; set('deployments', next); }}>Ниже</Button><Button type="button" variant="outline" disabled={value.deployments.length === 1} onClick={() => set('deployments', value.deployments.filter((_, j) => i !== j))}>Удалить deployment</Button></div></div>)}<Button type="button" variant="outline" disabled={value.deployments.length >= 5} onClick={() => set('deployments', [...value.deployments, { connection_id: '', generation: 1, model_id: '' }])}>Добавить deployment</Button></section>
  <section className="grid gap-4 md:grid-cols-3" aria-label="Лимиты профиля">{([['input_limit', 'Input, токены'], ['output_limit', 'Output, токены'], ['context_limit', 'Context, токены'], ['timeout_seconds', 'Общий timeout, секунды'], ['max_attempts', 'Максимум попыток']] as const).map(([key, label]) => <FormField key={key} id={`profile-${key}`} label={label} required>{attrs => <Input {...attrs} type="number" min={1} max={key === 'timeout_seconds' ? 600 : key === 'max_attempts' ? 5 : 4294967295} step={1} value={value[key] || ''} onChange={e => set(key, Number(e.target.value))}/>}</FormField>)}</section>
  <section className="grid gap-4 md:grid-cols-3" aria-label="Параметры генерации"><FormField id="profile-temperature" label="Temperature" hint="Не задано — параметр не отправляется.">{attrs => <Input {...attrs} type="number" step="any" min={0} max={2} value={value.parameters.temperature ?? ''} onChange={e => set('parameters', { ...value.parameters, temperature: e.target.value === '' ? undefined : Number(e.target.value) })}/>}</FormField><FormField id="profile-top-p" label="Top P" hint="Больше 0, не больше 1.">{attrs => <Input {...attrs} type="number" step="any" min={0} max={1} value={value.parameters.top_p ?? ''} onChange={e => set('parameters', { ...value.parameters, top_p: e.target.value === '' ? undefined : Number(e.target.value) })}/>}</FormField><FormField id="profile-reasoning" label="Reasoning effort">{attrs => <Input {...attrs} value={value.parameters.reasoning_effort ?? ''} maxLength={32} onChange={e => set('parameters', { ...value.parameters, reasoning_effort: e.target.value || undefined })}/>}</FormField></section>
  <div className="grid gap-5 md:grid-cols-2"><fieldset className="space-y-2"><legend className="mb-2 font-medium">Обязательные capabilities</legend>{caps.map(c => <label key={c} className="flex items-center gap-2"><input type="checkbox" checked={value.required_capabilities.includes(c)} onChange={e => set('required_capabilities', e.target.checked ? [...value.required_capabilities, c] : value.required_capabilities.filter(v => v !== c))}/>{c}</label>)}</fieldset><fieldset className="space-y-2"><legend className="mb-2 font-medium">Разрешённые caller overrides</legend>{overrides.map(c => <label key={c} className="flex items-center gap-2"><input type="checkbox" checked={(value.allowed_overrides ?? []).includes(c)} onChange={e => set('allowed_overrides', e.target.checked ? [...(value.allowed_overrides ?? []), c] : (value.allowed_overrides ?? []).filter(v => v !== c))}/>{c}</label>)}<p className="text-sm text-text-secondary">По умолчанию переопределения запрещены.</p></fieldset></div></fieldset>;
}
